-- MySQL Script generated by MySQL Workbench
-- Ter 17 Mai 2016 17:19:54 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unifei_soccer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unifei_soccer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unifei_soccer` DEFAULT CHARACTER SET utf8 ;
USE `unifei_soccer` ;

-- -----------------------------------------------------
-- Table `unifei_soccer`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unifei_soccer`.`equipes` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `titulos` INT NULL,
  PRIMARY KEY (`id_equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unifei_soccer`.`campeonatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unifei_soccer`.`campeonatos` (
  `id_campeonato` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `campeao` INT NULL,
  `vice` INT NULL,
  PRIMARY KEY (`id_campeonato`, `campeao`, `vice`),
  INDEX `fk_campeonatos_equipes1_idx` (`campeao` ASC),
  INDEX `fk_campeonatos_equipes2_idx` (`vice` ASC),
  CONSTRAINT `fk_campeonatos_equipes1`
    FOREIGN KEY (`campeao`)
    REFERENCES `unifei_soccer`.`equipes` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campeonatos_equipes2`
    FOREIGN KEY (`vice`)
    REFERENCES `unifei_soccer`.`equipes` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unifei_soccer`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unifei_soccer`.`jogos` (
  `id_jogo` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIMESTAMP NULL,
  `hora_fim` TIMESTAMP NULL,
  `data` DATE NULL,
  `finalizado` TINYINT(1) NOT NULL,
  `campo_nome` VARCHAR(255) NOT NULL,
  `campo_dimensao` VARCHAR(255) NOT NULL,
  `campeonatos_id_campeonato` INT NOT NULL,
  `campeonatos_campeao` INT NOT NULL,
  `campeonatos_vice` INT NOT NULL,
  PRIMARY KEY (`id_jogo`, `campeonatos_id_campeonato`, `campeonatos_campeao`, `campeonatos_vice`),
  INDEX `fk_jogos_campeonatos1_idx` (`campeonatos_id_campeonato` ASC, `campeonatos_campeao` ASC, `campeonatos_vice` ASC),
  CONSTRAINT `fk_jogos_campeonatos1`
    FOREIGN KEY (`campeonatos_id_campeonato` , `campeonatos_campeao` , `campeonatos_vice`)
    REFERENCES `unifei_soccer`.`campeonatos` (`id_campeonato` , `campeao` , `vice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unifei_soccer`.`jogadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unifei_soccer`.`jogadores` (
  `id_jogador` INT NOT NULL AUTO_INCREMENT,
  `id_equipe` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `posicao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_jogador`, `id_equipe`),
  INDEX `fk_jogador_equipe_idx` (`id_equipe` ASC),
  CONSTRAINT `fk_jogador_equipe`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `unifei_soccer`.`equipes` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unifei_soccer`.`arbitros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unifei_soccer`.`arbitros` (
  `id_arbitro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `tipo` ENUM('principal', 'auxiliar') NULL,
  PRIMARY KEY (`id_arbitro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unifei_soccer`.`sumulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unifei_soccer`.`sumulas` (
  `id_jogo` INT NOT NULL AUTO_INCREMENT,
  `id_sumula` INT NOT NULL,
  `log` TEXT NULL,
  `id_equipe1` INT NOT NULL,
  `id_equipe2` INT NOT NULL,
  `id_arbitro` INT NOT NULL,
  PRIMARY KEY (`id_jogo`, `id_sumula`, `id_equipe1`, `id_equipe2`, `id_arbitro`),
  INDEX `fk_sumula_jogo1_idx` (`id_jogo` ASC),
  INDEX `fk_sumula_equipe1_idx` (`id_equipe1` ASC),
  INDEX `fk_sumula_equipe2_idx` (`id_equipe2` ASC),
  INDEX `fk_sumula_arbitro1_idx` (`id_arbitro` ASC),
  CONSTRAINT `fk_sumula_jogo1`
    FOREIGN KEY (`id_jogo`)
    REFERENCES `unifei_soccer`.`jogos` (`id_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sumula_equipe1`
    FOREIGN KEY (`id_equipe1`)
    REFERENCES `unifei_soccer`.`equipes` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sumula_equipe2`
    FOREIGN KEY (`id_equipe2`)
    REFERENCES `unifei_soccer`.`equipes` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sumula_arbitro1`
    FOREIGN KEY (`id_arbitro`)
    REFERENCES `unifei_soccer`.`arbitros` (`id_arbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unifei_soccer`.`sumulasView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unifei_soccer`.`sumulasView` (
  `id_jogo` INT NOT NULL AUTO_INCREMENT,
  `id_sumula` INT NOT NULL,
  `log` VARCHAR(255) NULL,
  PRIMARY KEY (`id_jogo`, `id_sumula`),
  INDEX `fk_sumula_jogo1_idx` (`id_jogo` ASC),
  CONSTRAINT `fk_sumula_jogo10`
    FOREIGN KEY (`id_jogo`)
    REFERENCES `unifei_soccer`.`jogos` (`id_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
