-- MySQL Script generated by MySQL Workbench
-- Qui 05 Mai 2016 15:15:54 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jogos` (
  `id_jogo` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIMESTAMP NOT NULL,
  `hora_fim` TIMESTAMP NOT NULL,
  `data` DATE NOT NULL,
  `finalizado` TINYINT(1) NOT NULL,
  `campo_nome` VARCHAR(255) NOT NULL,
  `campo_dimensao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_jogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipes` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `titulos` INT NULL,
  PRIMARY KEY (`id_equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jogadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jogadores` (
  `id_jogador` INT NOT NULL,
  `id_equipe` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `posicao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_jogador`, `id_equipe`),
  INDEX `fk_jogador_equipe_idx` (`id_equipe` ASC),
  CONSTRAINT `fk_jogador_equipe`
    FOREIGN KEY (`id_equipe`)
    REFERENCES `mydb`.`equipes` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`arbitros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`arbitros` (
  `id_arbitro` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `tipo` ENUM('principal', 'auxiliar') NULL,
  PRIMARY KEY (`id_arbitro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sumulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sumulas` (
  `id_jogo` INT NOT NULL,
  `id_sumula` INT NOT NULL,
  `log` TEXT NULL,
  `id_equipe1` INT NOT NULL,
  `id_equipe2` INT NOT NULL,
  `id_arbitro` INT NOT NULL,
  PRIMARY KEY (`id_jogo`, `id_sumula`, `id_equipe1`, `id_equipe2`, `id_arbitro`),
  INDEX `fk_sumula_jogo1_idx` (`id_jogo` ASC),
  INDEX `fk_sumula_equipe1_idx` (`id_equipe1` ASC),
  INDEX `fk_sumula_equipe2_idx` (`id_equipe2` ASC),
  INDEX `fk_sumula_arbitro1_idx` (`id_arbitro` ASC),
  CONSTRAINT `fk_sumula_jogo1`
    FOREIGN KEY (`id_jogo`)
    REFERENCES `mydb`.`jogos` (`id_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sumula_equipe1`
    FOREIGN KEY (`id_equipe1`)
    REFERENCES `mydb`.`equipes` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sumula_equipe2`
    FOREIGN KEY (`id_equipe2`)
    REFERENCES `mydb`.`equipes` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sumula_arbitro1`
    FOREIGN KEY (`id_arbitro`)
    REFERENCES `mydb`.`arbitros` (`id_arbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sumulasView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sumulasView` (
  `id_jogo` INT NOT NULL,
  `id_sumula` INT NOT NULL,
  `log` VARCHAR(255) NULL,
  PRIMARY KEY (`id_jogo`, `id_sumula`),
  INDEX `fk_sumula_jogo1_idx` (`id_jogo` ASC),
  CONSTRAINT `fk_sumula_jogo10`
    FOREIGN KEY (`id_jogo`)
    REFERENCES `mydb`.`jogos` (`id_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
